apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8sclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8sclient
  template:
    metadata:
      labels:
        app: k8sclient
    spec:
      serviceAccountName: default
      containers:
        - image: <REGISTRY>/<NAME>:<TAG>
          name: k8sclient
          imagePullPolicy: Always
          env:
            - name: SERVER_PORT
              value: '8080'
            - name: LOG_LEVEL
              value: INFO