kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: depdraw-{{ default .Release.Name "api-server" }}
  namespace: depdraw
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      namespace: depdraw
      name: {{ .Release.Name }}-api-server:latest
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      env:
      - name: MAVEN_ARGS_APPEND
        value: {{ default .Values.mvnXtraArgs "-Dquarkus.package.type=uber-jar -pl api-server --also-make" }}
      - name: ARTIFACT_DIR
        value: {{ default .Values.artifactDir "api-server/target/" }}
      - name: MODULE_DIR
        value: {{ default .Values.module "api-server" }}
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi8/openjdk-17:1.14'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/nemerna/DepDraw.git'
    contextDir: src
  triggers:
    - type: ConfigChange
  runPolicy: Serial

---

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Release.Name }}-api-server
  namespace: {{ .Release.Namespace }}