apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name }}-dataservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Release.Name }}-dataservice
  template:
    metadata:
      labels:
        app: {{.Release.Name }}-dataservice
    spec:
      serviceAccountName: default
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/depdraw/{{ .Release.Name }}-dataservice:latest
        name: {{.Release.Name }}-dataservice
        imagePullPolicy: Always