kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-dataservice
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: {{.Release.Name }}-dataservice
  type: ClusterIP