apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Release.Name }}-dataservice-test
  annotations:
    "helm.sh/hook": test
spec:
  template:
    spec:
      containers:
      - name: {{.Release.Name }}-dataservice-test
        image: busybox
        command:
        - wget
        - -qO-
        - "http://{{.Release.Name }}-dataservice/health"
      restartPolicy: Never
  backoffLimit: 4