{{ if .Values.build }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: depdraw-{{ default .Values.image "transformer" }}
  namespace: depdraw
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      namespace: depdraw
      name: {{ .Release.Name }}-transformer:latest
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      env:
      - name: MAVEN_ARGS_APPEND
        value: {{ .Values.mvnXtraArgs }}
      - name: ARTIFACT_DIR
        value: transformer/target/
      - name: MODULE_DIR
        value: transformer
      from:
        kind: DockerImage
        name: 'registry.access.redhat.com/ubi8/openjdk-17:1.14'
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.ghRepo }}
    contextDir: src
  triggers:
    - type: ConfigChange
  runPolicy: Serial
{{ end }}

---

{{ if .Values.build }}

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Release.Name }}-transformer
  namespace: {{ .Release.Namespace }}
{{ end }}