apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: depdraw-{{ default .Release.Name "k8sclient" }}
  namespace: {{ .Release.Namespace }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: depdraw-{{ default .Release.Name "k8sclient" }}:latest
      namespace: {{ .Release.Namespace }}
  postCommit: {}
  source:
    git:
      uri: {{ default "https://github.com/nemerna/DepDraw.git" .Values.ghRepo }}
    contextDir: src/k8sclient
    type: Git
  strategy:
    type: Docker
    dockerStrategy: {}
  triggers:
  - type: ConfigChange

---

{{ if .Values.build }}

apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: depdraw-{{ default .Release.Name "k8sclient" }}
  namespace: {{ .Release.Namespace }}

{{ end }}